name: Playwright Tests
on:
 push:
    branches: [main]
jobs:
    webuitests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout
                        
                        
